language: node_js

node_js:
  - "lts/*" # Most recent LTS version,

services:
  - docker

cache: false

## before install phase
before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport
  
## install dependecy required
install:
  - "bin/installDeps.sh"
  - "cd src && npm install && cd -"
  - "npm install -g etherpad-load-test"

## environment variables that are global to matrix
env:
  global:
    ## encrypt sensitive data 
    - secure: "WMGxFkOeTTlhWB+ChMucRtIqVmMbwzYdNHuHQjKCcj8HBEPdZLfCuK/kf4rG\nVLcLQiIsyllqzNhBGVHG1nyqWr0/LTm8JRqSCDDVIhpyzp9KpCJQQJG2Uwjk\n6/HIJJh/wbxsEdLNV2crYU/EiVO3A4Bq0YTHUlbhUqG3mSCr5Ec="
    - secure: "gejXUAHYscbR6Bodw35XexpToqWkv2ifeECsbeEmjaLkYzXmUUNWJGknKSu7\nEUsSfQV8w+hxApr1Z+jNqk9aX3K1I4btL3cwk2trnNI8XRAvu1c1Iv60eerI\nkE82Rsd5lwUaMEh+/HoL8ztFCZamVndoNgX7HWp5J/NRZZMmh4g="

jobs:
  include:
    - name: "Backend test"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Load test"
      install: 
        - "npm install -g etherpad-load-test"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"
## Dockerfile tests
#    - name: "Test the Dockerfile"
#      install:
#        - "cd src && npm install && cd -"
#      script:
#        - "docker build -t etherpad:test ."
#        - "docker run -d -p 9001:9001 etherpad:test && sleep 3"
#        - "cd src && npm run test-container"pppp



notifications:
  # notify build results through email
  email:
  - wonweicheng@gmail.com 
