language: node_js

node_js:
  - "lts/*" # Most recent LTS version,

dist: xenial

cache: none


  
## install dependecy required
install:
  - "bin/installDeps.sh"
  - "cd src && npm install && cd -"
  - "npm install -g etherpad-load-test"
  - "npm install -g istanbul"

jobs:
  include:
    - name: "Backend test"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Load test"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"

after_script:
    - "cd src && npm run coverage"
    
notifications:
  # notify build and test results through email
  email:
  - geminientan@hotmail.com 
