language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache: false

## before install phase
before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport

## install dependecy required
install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "npm install -g etherpad-load-test"
  - "cd src && npm install && cd -"
  
## run the test script
script:
  - "tests/frontend/travis/runner.sh"
  - "tests/frontend/travis/runnerLoadTest.sh"
  - "tests/frontend/travis/runnerBackend.sh"
  - "tests/frontend/travis/sauce_tunnel.sh"

