language: node_js

node_js:
  - "lts/*" # Most recent LTS version,

dist: xenial

cache: none

## before install phase, install Libreoffice on Ubuntu
before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa # install libreoffice through PPA
  - sudo apt-get update # update package
  - sudo apt-get -y install libreoffice # install libreoffice
  - sudo apt-get -y install libreoffice-pdfimport # install pdf import component for LibreOffice
  
## install dependecy required
install:
  - "bin/installDeps.sh"
  - "cd src && npm install && cd -"
  - "npm install -g etherpad-load-test"
  - "npm install -g istanbul"

jobs:
  include:
    - name: "Backend test"
      script:
        - "tests/frontend/travis/runnerBackend.sh"
    - name: "Load test"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"
    
notifications:
  # notify build and test results through email
  email:
  - geminientan@hotmail.com 
